resources:
  - name: go_example
    type: GitRepo
    configuration:
      path: raksha78/NativeStep
      branches:
        include: linux
      gitProvider: raksha78_github
       

pipelines:
  - name: go_build_pipeline
    steps:
      - name: build_go
        type: GoBuild
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: go_example_build_publish
          sourceLocation: .
          repository: go_local
          outputLocation: /tmp/dist
          outputFile: hello_output
          inputResources:
            - name: go_example
          integrations:
            - name: art_v
        execution:
          onStart:
            - buildDir=$(find_resource_variable $inputGitRepoResourceName resourcePath)
            - echo "******** buildDir - $buildDir"
            - pushd $buildDir
            - go get -insecure
            - popd
          onComplete:
            - echo "____________completed"
            - cd /tmp/dist
            - ls
      
