resources:
  - name: go_example
    type: GitRepo
    configuration:
      path: neha-mishraa/NativeStep
      branches:
        include: linux
      gitProvider: github_neha
      
  - name: go_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: go_info
      buildNumber: 1
         

pipelines:
  - name: go_build_pipeline
    steps:
      - name: build_go
        type: GoBuild
        configuration:
            environmentVariables:
                JFROG_CLI_BUILD_NAME: go_example_build
            sourceLocation: .
    #           resolverRepo: go_local
            repository: go_local
    #           noRegistry: true
            outputLocation: /tmp/dist
            outputFile: hello_output
            goCommand: build -o /tmp/dist/hello_output
            inputResources:
                - name: go_example
            integrations:
                - name: art_v
        execution:
            onStart:
#                 - buildDir=$(find_resource_variable $inputGitRepoResourceName resourcePath)
#                 - echo "******** buildDir - $buildDir"
#                 - pushd $buildDir
#                 - go get -insecure
#                 - popd
                - $res_go_example_1_resourcePath
                - Push-Location $res_go_example_1_resourcePath
                - go get -insecure
                - Pop-Location
                - go version



      - name: publish_go_module
        type: GoPublishModule
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: go_example_module_publish
            JFROG_CLI_BUILD_NUMBER: ${run_number}
          sourceLocation: .
          inputSteps:
            - name: build_go
          version: v0.0.2
          targetRepository: go_local
          autoPublishBuildInfo: true
          integrations:
            - name: art_v
          inputResources:
            - name: go_example
          outputResources:
            - name: go_info
