resources:
  - name: go_example
    type: GitRepo
    configuration:
      path: raksha78/NativeStep
      branches:
        include: powershell
      gitProvider: raksha78_github
      
  - name: go_rak
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: go_rak
      buildNumber: 1
       

pipelines:
  - name: go_build_pipeline
    configuration:
      nodePool: win_2019
    steps:
      - name: build_go
        type: GoBuild
        configuration:
        environmentVariables:
            JFROG_CLI_BUILD_NAME: go_example_build_publish
#           sourceLocation: .
#           resolverRepo: go_local
        repository: go_local
#           noRegistry: true
        outputLocation: /tmp/dist
        outputFile: hello_output
#         goCommand: build -o /tmp/dist/hello_output
        inputResources:
            - name: go_example
        integrations:
            - name: art_v
        execution:
        onStart:
            - $res_go_example_resourcePath
            - Push-Location $res_go_example_resourcePath
            - go get -insecure
            - Pop-Location
            - go version
        onComplete:
            - pwd
            - cd workspace
            - cd tmp
            - ls
      - name: publish_go_binary
        type: GoPublishBinary
        configuration:
          inputSteps:
            - name: build_go
          targetRepository: go_local
          integrations:
            - name: art_v
          outputResources:
            - name: go_rak
