resources:
  - name: npm_repo
    type: GitRepo
    configuration:
      path: neha-mishraa/npmHelloWorld
      gitProvider: github_neha
#   - name: npm_publish
#     type: BuildInfo
#     configuration:
#       sourceArtifactory: art_v
#       buildName: npm_publish
#       buildNumber: 1
      
pipelines:
  - name: npm
    steps:
      - name: build_npm
        type: NpmBuild
        configuration:
#           repositoryName: npm-virtual
          resolverRepo: npm-virtual
          sourceLocation: .
          inputResources:
            - name: npm_repo
          integrations:
            - name: art_v
#       - name: publish_npm
#         type: NpmPublish
#         configuration:
#           autoPublishBuildInfo: true
#           repositoryName: npm-virtual
#           inputSteps:
#             - name: build_npm
#           integrations:
#             - name: art_v
#           outputResources:
#             - name: npm_publish
    
