resources:
  - name: repo
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/NativeStep
      branches:
        include: ^powershell$
  - name: docker_rak
    type: BuildInfo
    configuration:
      sourceArtifactory: art_v
      buildName: docker_rak
      buildNumber: 1

pipelines: 
  - name: dockerPipe
    configuration:
      nodePool: win_2019
    steps:
      - name: buildStep
        type: DockerBuild
        configuration:
          affinityGroup: Together
          dockerFileLocation: . # optional, defaults to .
          dockerFileName: Dockerfile    # optional, defaults to Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img   
          dockerImageTag:  ${run_number}    
          inputResources:
              - name: repo  
      - name: pushStep
        type: DockerPush
        configuration:
          targetRepository: rak_docker 
          affinityGroup: Together
          integrations:
            - name: art_v 
          inputSteps:
            - name: buildStep  
          outputResources:
            - name: docker_rak
