resources:
  - name: repo
    type: GitRepo
    configuration:
      gitProvider: raksha78_github                     
      path: raksha78/NativeStep
      branches:
        include: ^linux$

pipelines: 
  - name: dockerPipe
    steps:
      - name: buildStep
        type: DockerBuild
        configuration:
          dockerFileLocation: . # optional, defaults to .
#           dockerFileName: Dockerfile    # optional, defaults to Dockerfile
          dockerImageName: dev.jfrog-pipelines.com/rak_docker/img   
          dockerImageTag:  ${run_number}    
          inputResources:
              - name: repo  
